### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by davidor** [AnalisiGuanyem/Barcelona_Inequalities_Map#1]
`estils.css` contains references to font files that you have not included in this repo. Check this line, for example: https://github.com/AnalisiGuanyem/Barcelona_Inequalities_Map/blob/master/website/estils.css#L3

**Comment by Rogerlamosca** [comment]
Hi davidor, 

I'm sorry but the actually this fonts are commercial and we can't distribute...
